//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authorization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public long Id { get; set; }
        public long ClientId { get; set; }
        public long MasterId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TechTypeModelId { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<int> RequestStatus { get; set; }
        public string Repairparts { get; set; }
    
        public virtual RequestStatus RequestStatus1 { get; set; }
        public virtual TechTypeModel TechTypeModel { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
